version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/web/Dockerfile
    volumes:
      - ./src:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"